files: ^odoo_tools/|^tests
default_language_version:
  python: python3.10

repos:
# black
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: debug-statements

# Flake8
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    name: flake8 except __init__.py
    exclude: __init__.py
  - id: flake8
    name: flake8 only __init__.py
    args: [--ignore=F401]  # ignore imported unused in __init__.py
    files: __init__.py

# pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade

# isort
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
  